### ISSUE TITLE
Controllers are not generated

### ISSUE THREAD

**Issue by danysz** [shimastripe/apig#1]
I succeed to compile, install and also to create an empty app with "apig new"
When I run "apig gen" is just creating the root files but not the relevant for the models I created.

**Comment by ElegantSoft** [comment]
any updates

**Comment by ElegantSoft** [comment]
@shimastripe

**Comment by shimastripe** [comment]
@danysz @ElegantSoft I fixed `Go@1.14` breaking API changes and migrated from travis ci to github actions. So please recheck main branch and follow readme and try!
